"""connection

Revision ID: 38136edc9b75
Revises: 5cb2b6d1c167
Create Date: 2024-04-09 15:29:37.534310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38136edc9b75'
down_revision = '5cb2b6d1c167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_id_person_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_order_id_person'), ['id_person'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['id_person'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_id_person'))
        batch_op.create_unique_constraint('order_id_person_key', ['id_person'])

    # ### end Alembic commands ###
