"""new

Revision ID: 5cb2b6d1c167
Revises: 3b0ad720fd3f
Create Date: 2024-04-09 13:49:29.500378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb2b6d1c167'
down_revision = '3b0ad720fd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('check', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.Column('addres', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_order'),
    sa.UniqueConstraint('id_person')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('ingridients', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('mass', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('order')
    # ### end Alembic commands ###
