"""empty message

Revision ID: dbf80a236075
Revises: 6064ee751e53
Create Date: 2024-04-25 19:30:22.474250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf80a236075'
down_revision = '6064ee751e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=False))
        batch_op.drop_column('addres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addres', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
